version: '3.7'

services:
  cms_api:
    build: ./simple_cms_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./simple_cms_api:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - cms_api.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - cms_db.env

volumes:
  postgres_data:
