version: '3.7'

services:
  cms_api:
    build: ./simple_cms_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./simple_cms_api:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      # django-specific variables
      - DEBUG=${DJANGO_DEBUG}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      # database variables
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
      - DATABASE=${DATABASE}
      # boto3 and dajngo-storages variables
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - AWS_S3_CUSTOM_DOMAIN=${AWS_S3_CUSTOM_DOMAIN_HOST}/${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_SECURE_URLS=${AWS_S3_SECURE_URLS}
      # CORS variables
      - CORS_ORIGIN_ALLOW_ALL=${CORS_ORIGIN_ALLOW_ALL}
      - CORS_ORIGIN_WHITELIST=${CORS_ORIGIN_WHITELIST}
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4563-4599:4563-4599'
      - '8080:8080'
    environment:
      - SERVICES=s3
      - DEBUG=${LOCALSTACK_DEBUG}
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './localstack_data:/tmp/localstack'

volumes:
  postgres_data:
