# Generated by Django 3.0.7 on 2020-07-12 10:49

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=customers.models.rename_file),
        ),
    ]
